/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Login.Login;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumn;

/**
 *
 * @author stevenodonoghue
 */
public class RootInter extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "Pa55w0rd!";
    private static final String dataCon = "jdbc:mysql://localhost:3306/ResultsSystem";

    Connection sqlConn = null;
    PreparedStatement preStatement = null;
    ResultSet resultSet = null;
    
    int q, i;
    /**
     * Creates new form RootInter
     */
    public RootInter() {
        initComponents();
    }
    
    public void inputDBAdminInfo (){
    try {
       Class.forName("com.mysql.cj.jdbc.Driver");
       sqlConn = DriverManager.getConnection(dataCon,username,password);
       preStatement = sqlConn.prepareStatement("SELECT * FROM ResultsSystem.Administrator");
       resultSet = preStatement.executeQuery();
       ResultSetMetaData stData = resultSet.getMetaData();
       
       q= stData.getColumnCount();
       DefaultTableModel RecordTable = (DefaultTableModel)adminListTable.getModel();
       RecordTable.setRowCount (0);
       
       while (resultSet.next()){
           Vector columnData = new Vector();
           
           for(i=1;i<=q;i++){
               columnData.add(resultSet.getString("adminId"));
               columnData.add(resultSet.getString("firstName"));
               columnData.add(resultSet.getString("lastName"));
               columnData.add(resultSet.getString("adminEmail"));
               columnData.add(resultSet.getString("password"));
           }
        RecordTable.addRow(columnData);
        }
       }
    catch (Exception ex)
        {
        JOptionPane.showMessageDialog(null, ex);
        }            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtAdminPassword = new javax.swing.JTextField();
        txtAdminId = new javax.swing.JTextField();
        txtAdminEmail = new javax.swing.JTextField();
        txtAdminFirstName = new javax.swing.JTextField();
        txtAdminLastName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminListTable = new javax.swing.JTable();
        rootLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 670));
        setPreferredSize(new java.awt.Dimension(1110, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Root Interface");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 38));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, 20));

        jLabel3.setText("Admin Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, 20));

        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 20));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        jButton1.setText("Add");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jButton2.setText("Update");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jButton3.setText("Delete");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));
        jPanel1.add(txtAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 160, -1));
        jPanel1.add(txtAdminId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, -1));
        jPanel1.add(txtAdminEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 160, -1));
        jPanel1.add(txtAdminFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 160, -1));
        jPanel1.add(txtAdminLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 1030, 160));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Admin Id", "First Name", "Last Name", "Email", "Password"
            }
        ));
        jScrollPane1.setViewportView(adminListTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1010, 370));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 1030, 390));

        rootLogout.setText("Logout");
        rootLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(rootLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rootLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootLogoutActionPerformed
        // TODO add your handling code here:
        Login returnLogin = new Login();
        returnLogin.setVisible(true);
        systemExitNewFrame();
    }//GEN-LAST:event_rootLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RootInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RootInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RootInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RootInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RootInter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminListTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rootLogout;
    private javax.swing.JTextField txtAdminEmail;
    private javax.swing.JTextField txtAdminFirstName;
    private javax.swing.JTextField txtAdminId;
    private javax.swing.JTextField txtAdminLastName;
    private javax.swing.JTextField txtAdminPassword;
    // End of variables declaration//GEN-END:variables

private void systemExitNewFrame()
    {
    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
